Started logging messages at Fri Mar 22 11:27:01 2024
Info:    Using UV tolerance 1e-06
Info:    Using UV tolerance 1e-06
Info:    HwNlibToTSLib options selected:
Info:        Points: On
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 240 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-06
Info:    Working on 0
Info:        Working on 88
Info:            Created 
Info:        Working on 89
Info:            Created 
Info:        Working on 145
Info:            Created 
Info:        Working on 244
Info:            Created 
Info:        Working on 369
Info:            Created 
Info:        Working on 527
Info:            Created 
Info:        Working on 709
Info:            Created 
Info:        Working on 926
Info:            Created 
Info:        Working on 1167
Info:            Created 
Info:        Working on 1398
Info:            Created 
Info:        Working on 1578
Info:            Created 
Info:        Working on 1713
Info:            Created 
Info:        Working on 1816
Info:            Created 
Info:        Working on 1916
Info:            Created 
Info:        Working on 1900
Info:            Created 
Info:        Working on 1795
Info:            Created 
Info:        Working on 1683
Info:            Created 
Info:        Working on 1435
Info:            Created 
Info:        Working on 1422
Info:            Created 
Info:        Working on 1196
Info:            Created 
Info:        Working on 957
Info:            Created 
Info:        Working on 742
Info:            Created 
Info:        Working on 557
Info:            Created 
Info:        Working on 397
Info:            Created 
Info:        Working on 263
Info:            Created 
Info:        Working on 154
Info:            Created 
Info:        Working on 8
Info:            Created 
Info:        Working on 131
Info:            Created 
Info:        Working on 132
Info:            Created 
Info:        Working on 212
Info:            Created 
Info:        Working on 332
Info:            Created 
Info:        Working on 343
Info:            Created 
Info:        Working on 221
Info:            Created 
Info:        Working on 12
Info:            Created 
Info:        Working on 198
Info:            Created 
Info:        Working on 199
Info:            Created 
Info:        Working on 298
Info:            Created 
Info:        Working on 443
Info:            Created 
Info:        Working on 458
Info:            Created 
Info:        Working on 308
Info:            Created 
Info:        Working on 17
Info:            Created 
Info:        Working on 285
Info:            Created 
Info:        Working on 271
Info:            Created 
Info:        Working on 26
Info:            Created 
Info:        Working on 567
Info:            Created 
Info:        Working on 761
Info:            Created 
Info:        Working on 592
Info:            Created 
Info:        Working on 48
Info:            Created 
Info:        Working on 589
Info:            Created 
Info:        Working on 356
Info:            Created 
Info:        Working on 355
Info:            Created 
Info:        Working on 914
Info:            Created 
Info:        Working on 1156
Info:            Created 
Info:        Working on 1255
Info:            Created 
Info:        Working on 1024
Info:            Created 
Info:        Working on 797
Info:            Created 
Info:        Working on 601
Info:            Created 
Info:        Working on 93
Info:            Created 
Info:        Working on 785
Info:            Created 
Info:        Working on 720
Info:            Created 
Info:        Working on 539
Info:            Created 
Info:        Working on 1187
Info:            Created 
Info:        Working on 1462
Info:            Created 
Info:        Working on 1608
Info:            Created 
Info:        Working on 1636
Info:            Created 
Info:        Working on 1501
Info:            Created 
Info:        Working on 1075
Info:            Created 
Info:        Working on 645
Info:            Created 
Info:        Working on 842
Info:            Created 
Info:        Working on 1011
Info:            Created 
Info:        Working on 168
Info:            Created 
Info:        Working on 687
Info:            Created 
Info:        Working on 277
Info:            Created 
Info:        Working on 502
Info:            Created 
Info:        Working on 411
Info:            Created 
Info:        Working on 340
Info:            Created 
Info:        Working on 231
Info:            Created 
Info:        Working on 511
Info:            Created 
Info:        Working on 351
Info:            Created 
Info:        Working on 850
Info:            Created 
Info:        Working on 1317
Info:            Created 
Info:        Working on 1389
Info:            Created 
Info:        Working on 514
Info:            Created 
Info:        Working on 996
Info:            Created 
Info:        Working on 1321
Info:            Created 
Info:        Working on 1418
Info:            Created 
Info:        Working on 1413
Info:            Created 
Info:        Working on 944
Info:            Created 
Info:        Working on 577
Info:            Created 
Info:        Working on 1003
Info:            Created 
Info:        Working on 1630
Info:            Created 
Info:        Working on 1631
Info:            Created 
Info:        Working on 1743
Info:            Created 
Info:        Working on 1744
Info:            Created 
Info:        Working on 1840
Info:            Created 
Info:        Working on 1841
Info:            Created 
Info:        Working on 1941
Info:            Created 
Info:        Working on 1942
Info:            Created 
Info:        Working on 2034
Info:            Created 
Info:        Working on 2035
Info:            Created 
Info:        Working on 2113
Info:            Created 
Info:        Working on 2114
Info:            Created 
Info:        Working on 2187
Info:            Created 
Info:        Working on 2188
Info:            Created 
Info:        Working on 2261
Info:            Created 
Info:        Working on 2262
Info:            Created 
Info:        Working on 2335
Info:            Created 
Info:        Working on 2336
Info:            Created 
Info:        Working on 2409
Info:            Created 
Info:        Working on 2410
Info:            Created 
Info:        Working on 2483
Info:            Created 
Info:        Working on 2484
Info:            Created 
Info:        Working on 2557
Info:            Created 
Info:        Working on 2558
Info:            Created 
Info:        Working on 2631
Info:            Created 
Info:        Working on 2632
Info:            Created 
Info:        Working on 2705
Info:            Created 
Info:        Working on 2706
Info:            Created 
Info:        Working on 2779
Info:            Created 
Info:        Working on 2780
Info:            Created 
Info:        Working on 2853
Info:            Created 
Info:        Working on 2854
Info:            Created 
Info:        Working on 2927
Info:            Created 
Info:        Working on 2928
Info:            Created 
Info:        Working on 3001
Info:            Created 
Info:        Working on 3002
Info:            Created 
Info:        Working on 3075
Info:            Created 
Info:        Working on 3076
Info:            Created 
Info:        Working on 3149
Info:            Created 
Info:        Working on 3150
Info:            Created 
Info:        Working on 3223
Info:            Created 
Info:        Working on 3224
Info:            Created 
Info:        Working on 3297
Info:            Created 
Info:        Working on 3298
Info:            Created 
Info:        Working on 3371
Info:            Created 
Info:        Working on 3372
Info:            Created 
Info:        Working on 3445
Info:            Created 
Info:        Working on 3446
Info:            Created 
Info:        Working on 3519
Info:            Created 
Info:        Working on 3520
Info:            Created 
Info:        Working on 3593
Info:            Created 
Info:        Working on 3594
Info:            Created 
Info:        Working on 3667
Info:            Created 
Info:        Working on 3668
Info:            Created 
Info:        Working on 3741
Info:            Created 
Info:        Working on 3742
Info:            Created 
Info:        Working on 3815
Info:            Created 
Info:        Working on 3816
Info:            Created 
Info:        Working on 3889
Info:            Created 
Info:        Working on 3890
Info:            Created 
Info:        Working on 3963
Info:            Created 
Info:        Working on 3964
Info:            Created 
Info:        Working on 4037
Info:            Created 
Info:        Working on 4038
Info:            Created 
Info:        Working on 4111
Info:            Created 
Info:        Working on 4112
Info:            Created 
Info:        Working on 4185
Info:            Created 
Info:        Working on 4186
Info:            Created 
Info:        Working on 4259
Info:            Created 
Info:        Working on 4260
Info:            Created 
Info:        Working on 4333
Info:            Created 
Info:        Working on 4334
Info:            Created 
Info:        Working on 4406
Info:            Created 
Info:        Working on 4407
Info:            Created 
Info:        Working on 4478
Info:            Created 
Info:        Working on 4479
Info:            Created 
Info:        Working on 4547
Info:            Created 
Info:        Working on 4548
Info:            Created 
Info:        Working on 4608
Info:            Created 
Info:        Working on 4609
Info:            Created 
Info:        Working on 694
Info:            Created 
Info:        Working on 1600
Info:            Created 
Info:        Working on 1532
Info:            Created 
Info:        Working on 908
Info:            Created 
Info:        Working on 1245
Info:            Created 
Info:        Working on 1604
Info:            Created 
Info:        Working on 1351
Info:            Created 
Info:        Working on 1152
Info:            Created 
Info:        Working on 1352
Info:            Created 
Info:        Working on 1529
Info:            Created 
Info:        Working on 1675
Info:            Created 
Info:        Working on 1789
Info:            Created 
Info:        Working on 1891
Info:            Created 
Info:        Working on 1992
Info:            Created 
Info:        Working on 1910
Info:            Created 
Info:        Working on 1806
Info:            Created 
Info:        Working on 1702
Info:            Created 
Info:        Working on 1378
Info:            Created 
Info:        Working on 1379
Info:            Created 
Info:        Working on 1692
Info:            Created 
Info:        Working on 1799
Info:            Created 
Info:        Working on 1756
Info:            Created 
Info:        Working on 1579
Info:            Created 
Info:        Working on 1404
Info:            Created 
Info:        Working on 1303
Info:            Created 
Info:        Working on 832
Info:            Created 
Info:        Working on 479
Info:            Created 
Info:        Working on 661
Info:            Created 
Info:        Working on 1092
Info:            Created 
Info:        Working on 1219
Info:            Created 
Info:        Working on 974
Info:            Created 
Info:        Working on 1434
Info:            Created 
Info:        Working on 1721
Info:            Created 
Info:        Working on 1516
Info:            Created 
Info:        Working on 1660
Info:            Created 
Info:        Working on 1773
Info:            Created 
Info:        Working on 1879
Info:            Created 
Info:        Working on 1987
Info:            Created 
Info:        Working on 2084
Info:            Created 
Info:        Working on 2165
Info:            Created 
Info:        Working on 2240
Info:            Created 
Info:        Working on 2314
Info:            Created 
Info:        Working on 2388
Info:            Created 
Info:        Working on 2462
Info:            Created 
Info:        Working on 2536
Info:            Created 
Info:        Working on 2610
Info:            Created 
Info:        Working on 2684
Info:            Created 
Info:        Working on 2758
Info:            Created 
Info:        Working on 2832
Info:            Created 
Info:        Working on 2906
Info:            Created 
Info:        Working on 2980
Info:            Created 
Info:        Working on 3054
Info:            Created 
Info:        Working on 3128
Info:            Created 
Info:        Working on 3202
Info:            Created 
Info:        Working on 3276
Info:            Created 
Info:        Working on 3350
Info:            Created 
Info:        Working on 3424
Info:            Created 
Info:        Working on 3498
Info:            Created 
Info:        Working on 3572
Info:            Created 
Info:        Working on 3646
Info:            Created 
Info:        Working on 3720
Info:            Created 
Info:        Working on 3794
Info:            Created 
Info:        Working on 3868
Info:            Created 
Info:        Working on 3942
Info:            Created 
Info:        Working on 4016
Info:            Created 
Info:        Working on 4090
Info:            Created 
Info:        Working on 4164
Info:            Created 
Info:        Working on 4238
Info:            Created 
Info:        Working on 4312
Info:            Created 
Info:        Working on 4386
Info:            Created 
Info:        Working on 4459
Info:            Created 
Info:        Working on 4531
Info:            Created 
Info:        Working on 4600
Info:            Created 
Info:        Working on 4661
Info:            Created 
Info:        Working on 4713
Info:            Created 
Info:        Working on 4755
Info:            Created 
Info:        Working on 4782
Info:            Created 
Info:        Working on 4795
Info:            Created 
Info:        Working on 871
Info:            Created 
Info:        Working on 1603
Info:            Created 
Info:        Working on 1238
Info:            Created 
Info:        Working on 1111
Info:            Created 
Info:        Working on 273
Info:            Created 
Info:        Working on 575
Info:            Created 
Info:        Working on 164
Info:            Created 
Info:        Working on 382
Info:            Created 
Info:        Working on 252
Info:            Created 
Info:        Working on 385
Info:            Created 
Info:        Working on 1582
Info:            Created 
Info:        Working on 1586
Info:            Created 
Info:        Working on 543
Info:            Created 
Info:        Working on 376
Info:            Created 
Info:        Working on 533
Info:            Created 
Info:        Working on 931
Info:            Created 
Info:        Working on 1172
Info:            Created 
Info:        Working on 717
Info:            Created 
Info:        Working on 813
Info:            Created 
Info:        Working on 1268
Info:            Created 
Info:        Working on 934
Info:            Created 
Info:        Working on 1174
Info:            Created 
Info:        Working on 802
Info:            Created 
Info:        Working on 1052
Info:            Created 
Info:        Working on 630
Info:            Created 
Info:        Working on 1042
Info:            Created 
Info:        Working on 1277
Info:            Created 
Info:        Working on 1479
Info:            Created 
Info:        Working on 1287
Info:            Created 
Info:        Working on 618
Info:            Created 
Info:        Working on 1639
Info:            Created 
Info:        Working on 1490
Info:            Created 
Info:        Working on 824
Info:            Created 
Info:        Working on 1055
Info:            Created 
Info:        Working on 1133
Info:            Created 
Info:        Working on 1386
Info:            Created 
Info:        Working on 1438
Info:            Created 
Info:        Working on 1221
Info:            Created 
Info:        Working on 1293
Info:            Created 
Info:        Working on 1304
Info:            Created 
Info:        Working on 834
Info:            Created 
Info:        Working on 1298
Info:            Created 
Info:        Working on 760
Info:            Created 
Info:        Working on 752
Info:            Created 
Info:        Working on 985
Info:            Created 
Info:        Working on 1222
Info:            Created 
Info:        Working on 1141
Info:            Created 
Info:        Working on 899
Info:            Created 
Info:        Working on 683
Info:            Created 
Info:        Working on 496
Info:            Created 
Info:        Working on 672
Info:            Created 
Info:        Working on 889
Info:            Created 
Info:        Working on 1136
Info:            Created 
Info:        Working on 1383
Info:            Created 
Info:        Working on 1261
Info:            Created 
Info:        Working on 1227
Info:            Created 
Info:        Working on 1403
Info:            Created 
Info:        Working on 1206
Info:            Created 
Info:        Working on 968
Info:            Created 
Info:        Working on 473
Info:            Created 
Info:        Working on 655
Info:            Created 
Info:        Working on 322
Info:            Created 
Info:        Working on 1695
Info:            Created 
Info:        Working on 1556
Info:            Created 
Info:        Working on 483
Info:            Created 
Info:        Working on 665
Info:            Created 
Info:        Working on 875
Info:            Created 
Info:        Working on 1115
Info:            Created 
Info:        Working on 1356
Info:            Created 
Info:        Working on 1543
Info:            Created 
Info:        Working on 1686
Info:            Created 
Info:        Working on 2014
Info:            Created 
Info:        Working on 2091
Info:            Created 
Info:        Working on 1798
Info:            Created 
Info:        Working on 1904
Info:            Created 
Info:        Working on 2001
Info:            Created 
Info:        Working on 2090
Info:            Created 
Info:        Working on 2003
Info:            Created 
Info:        Working on 2011
Info:            Created 
Info:        Working on 1899
Info:            Created 
Info:        Working on 1996
Info:            Created 
Info:        Working on 1794
Info:            Created 
Info:        Working on 1680
Info:            Created 
Info:        Working on 1540
Info:            Created 
Info:        Working on 1597
Info:            Created 
Info:        Working on 1429
Info:            Created 
Info:        Working on 1592
Info:            Created 
Info:        Working on 1426
Info:            Created 
Info:        Working on 1203
Info:            Created 
Info:        Working on 1089
Info:            Created 
Info:        Working on 1083
Info:            Created 
Info:        Working on 1319
Info:            Created 
Info:        Working on 857
Info:            Created 
Info:        Working on 465
Info:            Created 
Info:        Working on 640
Info:            Created 
Info:        Working on 454
Info:            Created 
Info:        Working on 633
Info:            Created 
Info:        Working on 838
Info:            Created 
Info:        Working on 1070
Info:            Created 
Info:        Working on 1307
Info:            Created 
Info:        Working on 1776
Info:            Created 
Info:        Working on 1500
Info:            Created 
Info:        Working on 1882
Info:            Created 
Info:        Working on 1647
Info:            Created 
Info:        Working on 1990
Info:            Created 
Info:        Working on 1760
Info:            Created 
Info:        Working on 2087
Info:            Created 
Info:        Working on 1866
Info:            Created 
Info:        Working on 2167
Info:            Created 
Info:        Working on 1974
Info:            Created 
Info:        Working on 2228
Info:            Created 
Info:        Working on 2072
Info:            Created 
Info:        Working on 1857
Info:            Created 
Info:        Working on 1966
Info:            Created 
Info:        Working on 1753
Info:            Created 
Info:        Working on 1862
Info:            Created 
Info:        Working on 1969
Info:            Created 
Info:        Working on 2302
Info:            Created 
Info:        Working on 2067
Info:            Created 
Info:        Working on 1958
Info:            Created 
Info:        Working on 2059
Info:            Created 
Info:        Working on 1850
Info:            Created 
Info:        Working on 1963
Info:            Created 
Info:        Working on 2062
Info:            Created 
Info:        Working on 2376
Info:            Created 
Info:        Working on 2146
Info:            Created 
Info:        Working on 2051
Info:            Created 
Info:        Working on 2138
Info:            Created 
Info:        Working on 1951
Info:            Created 
Info:        Working on 2056
Info:            Created 
Info:        Working on 2141
Info:            Created 
Info:        Working on 2450
Info:            Created 
Info:        Working on 2220
Info:            Created 
Info:        Working on 2130
Info:            Created 
Info:        Working on 2212
Info:            Created 
Info:        Working on 2044
Info:            Created 
Info:        Working on 2135
Info:            Created 
Info:        Working on 2215
Info:            Created 
Info:        Working on 2524
Info:            Created 
Info:        Working on 2294
Info:            Created 
Info:        Working on 2204
Info:            Created 
Info:        Working on 2286
Info:            Created 
Info:        Working on 2123
Info:            Created 
Info:        Working on 2209
Info:            Created 
Info:        Working on 2289
Info:            Created 
Info:        Working on 2598
Info:            Created 
Info:        Working on 2368
Info:            Created 
Info:        Working on 2278
Info:            Created 
Info:        Working on 2360
Info:            Created 
Info:        Working on 2197
Info:            Created 
Info:        Working on 2283
Info:            Created 
Info:        Working on 2363
Info:            Created 
Info:        Working on 2672
Info:            Created 
Info:        Working on 2442
Info:            Created 
Info:        Working on 2352
Info:            Created 
Info:        Working on 2434
Info:            Created 
Info:        Working on 2271
Info:            Created 
Info:        Working on 2357
Info:            Created 
Info:        Working on 2437
Info:            Created 
Info:        Working on 2746
Info:            Created 
Info:        Working on 2516
Info:            Created 
Info:        Working on 2426
Info:            Created 
Info:        Working on 2508
Info:            Created 
Info:        Working on 2345
Info:            Created 
Info:        Working on 2431
Info:            Created 
Info:        Working on 2511
Info:            Created 
Info:        Working on 2820
Info:            Created 
Info:        Working on 2590
Info:            Created 
Info:        Working on 2500
Info:            Created 
Info:        Working on 2582
Info:            Created 
Info:        Working on 2419
Info:            Created 
Info:        Working on 2505
Info:            Created 
Info:        Working on 2585
Info:            Created 
Info:        Working on 2894
Info:            Created 
Info:        Working on 2664
Info:            Created 
Info:        Working on 2574
Info:            Created 
Info:        Working on 2656
Info:            Created 
Info:        Working on 2493
Info:            Created 
Info:        Working on 2579
Info:            Created 
Info:        Working on 2659
Info:            Created 
Info:        Working on 2968
Info:            Created 
Info:        Working on 2738
Info:            Created 
Info:        Working on 2648
Info:            Created 
Info:        Working on 2730
Info:            Created 
Info:        Working on 2567
Info:            Created 
Info:        Working on 2653
Info:            Created 
Info:        Working on 2733
Info:            Created 
Info:        Working on 3042
Info:            Created 
Info:        Working on 2812
Info:            Created 
Info:        Working on 2722
Info:            Created 
Info:        Working on 2804
Info:            Created 
Info:        Working on 2641
Info:            Created 
Info:        Working on 2727
Info:            Created 
Info:        Working on 2807
Info:            Created 
Info:        Working on 3116
Info:            Created 
Info:        Working on 2886
Info:            Created 
Info:        Working on 2796
Info:            Created 
Info:        Working on 2878
Info:            Created 
Info:        Working on 2715
Info:            Created 
Info:        Working on 2801
Info:            Created 
Info:        Working on 2881
Info:            Created 
Info:        Working on 3190
Info:            Created 
Info:        Working on 2960
Info:            Created 
Info:        Working on 2870
Info:            Created 
Info:        Working on 2952
Info:            Created 
Info:        Working on 2789
Info:            Created 
Info:        Working on 2875
Info:            Created 
Info:        Working on 2955
Info:            Created 
Info:        Working on 3264
Info:            Created 
Info:        Working on 3034
Info:            Created 
Info:        Working on 2944
Info:            Created 
Info:        Working on 3026
Info:            Created 
Info:        Working on 2863
Info:            Created 
Info:        Working on 2949
Info:            Created 
Info:        Working on 3029
Info:            Created 
Info:        Working on 3338
Info:            Created 
Info:        Working on 3108
Info:            Created 
Info:        Working on 3018
Info:            Created 
Info:        Working on 3100
Info:            Created 
Info:        Working on 2937
Info:            Created 
Info:        Working on 3023
Info:            Created 
Info:        Working on 3103
Info:            Created 
Info:        Working on 3412
Info:            Created 
Info:        Working on 3182
Info:            Created 
Info:        Working on 3092
Info:            Created 
Info:        Working on 3174
Info:            Created 
Info:        Working on 3011
Info:            Created 
Info:        Working on 3097
Info:            Created 
Info:        Working on 3177
Info:            Created 
Info:        Working on 3486
Info:            Created 
Info:        Working on 3256
Info:            Created 
Info:        Working on 3166
Info:            Created 
Info:        Working on 3248
Info:            Created 
Info:        Working on 3085
Info:            Created 
Info:        Working on 3171
Info:            Created 
Info:        Working on 3251
Info:            Created 
Info:        Working on 3560
Info:            Created 
Info:        Working on 3330
Info:            Created 
Info:        Working on 3240
Info:            Created 
Info:        Working on 3322
Info:            Created 
Info:        Working on 3159
Info:            Created 
Info:        Working on 3245
Info:            Created 
Info:        Working on 3325
Info:            Created 
Info:        Working on 3634
Info:            Created 
Info:        Working on 3404
Info:            Created 
Info:        Working on 3314
Info:            Created 
Info:        Working on 3396
Info:            Created 
Info:        Working on 3233
Info:            Created 
Info:        Working on 3319
Info:            Created 
Info:        Working on 3399
Info:            Created 
Info:        Working on 3708
Info:            Created 
Info:        Working on 3478
Info:            Created 
Info:        Working on 3388
Info:            Created 
Info:        Working on 3470
Info:            Created 
Info:        Working on 3307
Info:            Created 
Info:        Working on 3393
Info:            Created 
Info:        Working on 3473
Info:            Created 
Info:        Working on 3782
Info:            Created 
Info:        Working on 3552
Info:            Created 
Info:        Working on 3462
Info:            Created 
Info:        Working on 3544
Info:            Created 
Info:        Working on 3381
Info:            Created 
Info:        Working on 3467
Info:            Created 
Info:        Working on 3547
Info:            Created 
Info:        Working on 3856
Info:            Created 
Info:        Working on 3626
Info:            Created 
Info:        Working on 3536
Info:            Created 
Info:        Working on 3618
Info:            Created 
Info:        Working on 3455
Info:            Created 
Info:        Working on 3541
Info:            Created 
Info:        Working on 3621
Info:            Created 
Info:        Working on 3930
Info:            Created 
Info:        Working on 3700
Info:            Created 
Info:        Working on 3610
Info:            Created 
Info:        Working on 3692
Info:            Created 
Info:        Working on 3529
Info:            Created 
Info:        Working on 3615
Info:            Created 
Info:        Working on 3695
Info:            Created 
Info:        Working on 4004
Info:            Created 
Info:        Working on 3774
Info:            Created 
Info:        Working on 3684
Info:            Created 
Info:        Working on 3766
Info:            Created 
Info:        Working on 3603
Info:            Created 
Info:        Working on 3689
Info:            Created 
Info:        Working on 3769
Info:            Created 
Info:        Working on 4078
Info:            Created 
Info:        Working on 3848
Info:            Created 
Info:        Working on 3758
Info:            Created 
Info:        Working on 3840
Info:            Created 
Info:        Working on 3677
Info:            Created 
Info:        Working on 3763
Info:            Created 
Info:        Working on 3843
Info:            Created 
Info:        Working on 4152
Info:            Created 
Info:        Working on 3922
Info:            Created 
Info:        Working on 3832
Info:            Created 
Info:        Working on 3914
Info:            Created 
Info:        Working on 3751
Info:            Created 
Info:        Working on 3837
Info:            Created 
Info:        Working on 3917
Info:            Created 
Info:        Working on 4226
Info:            Created 
Info:        Working on 3996
Info:            Created 
Info:        Working on 3906
Info:            Created 
Info:        Working on 3988
Info:            Created 
Info:        Working on 3825
Info:            Created 
Info:        Working on 3911
Info:            Created 
Info:        Working on 3991
Info:            Created 
Info:        Working on 4300
Info:            Created 
Info:        Working on 4070
Info:            Created 
Info:        Working on 3980
Info:            Created 
Info:        Working on 4062
Info:            Created 
Info:        Working on 3899
Info:            Created 
Info:        Working on 3985
Info:            Created 
Info:        Working on 4065
Info:            Created 
Info:        Working on 4374
Info:            Created 
Info:        Working on 4144
Info:            Created 
Info:        Working on 4054
Info:            Created 
Info:        Working on 4136
Info:            Created 
Info:        Working on 3973
Info:            Created 
Info:        Working on 4059
Info:            Created 
Info:        Working on 4139
Info:            Created 
Info:        Working on 4447
Info:            Created 
Info:        Working on 4218
Info:            Created 
Info:        Working on 4128
Info:            Created 
Info:        Working on 4210
Info:            Created 
Info:        Working on 4047
Info:            Created 
Info:        Working on 4133
Info:            Created 
Info:        Working on 4213
Info:            Created 
Info:        Working on 4519
Info:            Created 
Info:        Working on 4292
Info:            Created 
Info:        Working on 4202
Info:            Created 
Info:        Working on 4284
Info:            Created 
Info:        Working on 4121
Info:            Created 
Info:        Working on 4207
Info:            Created 
Info:        Working on 4287
Info:            Created 
Info:        Working on 4588
Info:            Created 
Info:        Working on 4366
Info:            Created 
Info:        Working on 4276
Info:            Created 
Info:        Working on 4358
Info:            Created 
Info:        Working on 4195
Info:            Created 
Info:        Working on 4281
Info:            Created 
Info:        Working on 4361
Info:            Created 
Info:        Working on 4649
Info:            Created 
Info:        Working on 4439
Info:            Created 
Info:        Working on 4350
Info:            Created 
Info:        Working on 4431
Info:            Created 
Info:        Working on 4269
Info:            Created 
Info:        Working on 4355
Info:            Created 
Info:        Working on 4434
Info:            Created 
Info:        Working on 4702
Info:            Created 
Info:        Working on 4511
Info:            Created 
Info:        Working on 4423
Info:            Created 
Info:        Working on 4503
Info:            Created 
Info:        Working on 4343
Info:            Created 
Info:        Working on 4428
Info:            Created 
Info:        Working on 4506
Info:            Created 
Info:        Working on 4745
Info:            Created 
Info:        Working on 4580
Info:            Created 
Info:        Working on 4495
Info:            Created 
Info:        Working on 4572
Info:            Created 
Info:        Working on 4416
Info:            Created 
Info:        Working on 4500
Info:            Created 
Info:        Working on 4575
Info:            Created 
Info:        Working on 4774
Info:            Created 
Info:        Working on 4641
Info:            Created 
Info:        Working on 4564
Info:            Created 
Info:        Working on 4633
Info:            Created 
Info:        Working on 4488
Info:            Created 
Info:        Working on 4569
Info:            Created 
Info:        Working on 4636
Info:            Created 
Info:        Working on 4792
Info:            Created 
Info:        Working on 4694
Info:            Created 
Info:        Working on 4625
Info:            Created 
Info:        Working on 4686
Info:            Created 
Info:        Working on 4557
Info:            Created 
Info:        Working on 4630
Info:            Created 
Info:        Working on 4689
Info:            Created 
Info:        Working on 4801
Info:            Created 
Info:        Working on 4737
Info:            Created 
Info:        Working on 4678
Info:            Created 
Info:        Working on 4729
Info:            Created 
Info:        Working on 4618
Info:            Created 
Info:        Working on 4683
Info:            Created 
Info:        Working on 4732
Info:            Created 
Info:        Working on 4804
Info:            Created 
Info:        Working on 4766
Info:            Created 
Info:        Working on 4721
Info:            Created 
Info:        Working on 4759
Info:            Created 
Info:        Working on 4671
Info:            Created 
Info:        Working on 4726
Info:            Created 
Info:        Working on 4761
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 1.19511e-06
Info:        Using 3D tolerance 1e-06
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Fri Mar 22 11:27:01 2024
